# Generated by Django 4.2.4 on 2023-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="is_deleted",
        ),
    ]
