# Generated by Django 4.2.4 on 2023-08-02 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blogpost_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
